/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Login;

import Controller.LoginController;
import DAO.UsersDAOImpl;
import Entity.User;
import UI.Main_Form;
import Util.XAuth;
import Util.XDialog;
import com.formdev.flatlaf.fonts.roboto.FlatRobotoFont;
import com.formdev.flatlaf.themes.FlatMacLightLaf;
import java.awt.Font;
import javax.swing.UIManager;

/**
 *
 * @author mphuc
 */
public class Login extends javax.swing.JDialog implements LoginController {

    /**
     * Creates new form Login
     */
    public Login(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Hệ Thống Quản Lý Trường Học - Đăng Nhập");
        txtMaso.putClientProperty("JTextField.placeholderText", "Nhập mã số giáo viên");
        txtPassword.putClientProperty("JTextField.placeholderText", "Mật khẩu");
        txtMaso.requestFocusInWindow();
    }

    Login() {
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtMaso = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txtPassword = new javax.swing.JPasswordField();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel2.setText("HỆ THỐNG QUẢN LÝ");

        jLabel4.setText("Mã Số Giáo Viên");

        txtMaso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMasoActionPerformed(evt);
            }
        });

        jLabel5.setText("Mật Khẩu");

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("Đăng Nhập");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 102, 255));
        jButton2.setForeground(new java.awt.Color(0, 102, 204));
        jButton2.setText("Quên mật khẩu?");
        jButton2.setBorder(null);
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel6.setText("Điểm & Lớp Học");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton2)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel4)
                                .addComponent(txtMaso)
                                .addComponent(jLabel5)
                                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 331, Short.MAX_VALUE)
                                .addComponent(txtPassword))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(jLabel2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(jLabel6)))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMaso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(85, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(388, 388, 388)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(388, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(90, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        login();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtMasoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMasoActionPerformed
        // TODO add your handling code here
        txtPassword.requestFocus();
    }//GEN-LAST:event_txtMasoActionPerformed

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
        login();
    }//GEN-LAST:event_txtPasswordActionPerformed

    public static void main(String args[]) {
        FlatMacLightLaf.setup();
        UIManager.put("defaultFont", new Font(FlatRobotoFont.FAMILY, Font.PLAIN, 13));
        UIManager.put("PasswordField.showRevealButton", true);
        UIManager.put("PasswordField.showCapsLock", true);
        UIManager.put("Button.arc", 20);
        UIManager.put("TextComponent.arc", 10);
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Login dialog = new Login(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtMaso;
    private javax.swing.JPasswordField txtPassword;
    // End of variables declaration//GEN-END:variables

    @Override
    public void open() {
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }

@Override
public void login() {
    String username = txtMaso.getText().trim();
    String password = new String(txtPassword.getPassword());

    if (username.isEmpty()) {
        XDialog.alert("Vui lòng nhập tên đăng nhập!");
        txtMaso.requestFocus();
        return;
    }

    if (password.isEmpty()) {
        XDialog.alert("Vui lòng nhập mật khẩu!");
        txtPassword.requestFocus();
        return;
    }

    try {
        UsersDAOImpl dao = new UsersDAOImpl();
        User user = dao.findById(username);

        if (user == null) {
            XDialog.alert("Tên đăng nhập không tồn tại!");
            txtMaso.requestFocus();
        } else if (!password.equals(user.getMatKhau())) {
            XDialog.alert("Sai mật khẩu đăng nhập!");
            txtPassword.requestFocus();
        } else if (!user.isActive()) {
            XDialog.alert("Tài khoản của bạn đang bị khoá!");
        } else {
            XAuth.user = user; // Lưu thông tin user
            
            this.dispose();
            
            // ✅ THÊM DÒNG NÀY:
            openMainForm(user);
        }
    } catch (Exception e) {
        XDialog.alert("Lỗi đăng nhập: " + e.getMessage());
        e.printStackTrace();
    }
}
    
private void openMainForm(User user) {
    // ✅ THÊM KIỂM TRA NULL
    if (user == null) {
        System.out.println("❌ ERROR: User is null!");
        XDialog.alert("Lỗi: Thông tin người dùng bị lỗi!");
        return;
    }
    
    java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            try {
                System.out.println("🔑 Đăng nhập thành công cho user: " + user.getMaNguoiDung());
                System.out.println("🎭 Vai trò: " + user.getMaVaiTro());

                Main_Form mainForm = new Main_Form();
                mainForm.setCurrentUser(user); // 🔥 QUAN TRỌNG!
                
                mainForm.setTitle("Hệ Thống Quản Lý - " + user.getTenNguoiDung());
                mainForm.setLocationRelativeTo(null);
                mainForm.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
                mainForm.setVisible(true);

                System.out.println("✅ Main_Form đã mở thành công!");

            } catch (Exception e) {
                System.out.println("💥 Lỗi mở Main_Form: " + e.getMessage());
                XDialog.alert("Lỗi khi mở giao diện: " + e.getMessage());
                e.printStackTrace();
            }
        }
    });
}

    @Override
    public void exit() {
        if (XDialog.confirm("Bạn muốn tắt ứng dụng?")) {
            System.exit(0);
        }
    }
}
